### ISSUE TITLE
ETC sent from Coinspot to Bancor - Not received

### ISSUE THREAD

**Issue by stephensumner** [ethereumclassic/explorer#321]
I sent ETC from Coinspot to Bancor. 
Bancor apparently do not use ETC and now my funds are missing. Neither wallet will help recover the funds. They've said to contact the blockchain. I have no idea what that means. 
Can anyone help?

**Comment by kek-mex** [comment]
This has nothing to do with this project. Contact Bancor, they're the only ones that can help you, if you accidently sent ETC to ETH address.

**Comment by FrankDev34** [comment]
Talk to Bancor Support on the [Live support page](https://support-bancornetwork.com) so that your issue can be looked into.
