### ISSUE TITLE
Statebot integration

### ISSUE THREAD

**Issue by elaineo** [ethereumclassic/explorer#60]
statebot.info the easiest way to access it is to contract on etc to get the json link and use ipfs.io/ipfs/%theFileHash%

**Comment by realcodywburns** [comment]
Im working on a central repository for all my contracts with version tracking and ipfs linking for abi files. So in the future you can call my repo, ask for the latest version of statebot(or other contracts) and have it return the address to the latest version and abi. It will have version tracking as well so things like the token registry can remember which version of the token contract was used,  and ask for that specific abi. I would think organizations would use something like this in the future for contract management.
